## Análise Exploratória de Dados (EDA)

### 1. Visão Geral dos Dados

In [14]:
import pandas as pd
from google.colab import files
import io

print("Por favor, selecione o primeiro arquivo CSV para df1:")
uploaded_df1 = files.upload()

# Assuming only one file is uploaded
for filename in uploaded_df1.keys():
  df1 = pd.read_csv(io.BytesIO(uploaded_df1[filename]))
  print(f"O arquivo '{filename}' foi carregado com sucesso em df1.")
  display(df1.head())
  break # Process only the first uploaded file

Por favor, selecione o primeiro arquivo CSV para df1:

Saving dados_sinasc_trabalho_projeto_2022.csv to dados_sinasc_trabalho_projeto_2022 (1).csv
O arquivo 'dados_sinasc_trabalho_projeto_2022 (1).csv' foi carregado com sucesso em df1.

,ano,sigla_uf,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,data_nascimento,tipo_parto_1
0,2022,AC,1.0,1200344.0,4.0,4.0,0.0,24.0,1.0,5.0,35.0,2022-03-18,1.0
1,2022,AC,1.0,1200328.0,2.0,2.0,0.0,15.0,4.0,5.0,34.0,2022-12-30,1.0
2,2022,AC,9.0,1200351.0,5.0,5.0,0.0,34.0,1.0,5.0,38.0,2022-01-20,9.0
3,2022,AC,1.0,1200328.0,1.0,1.0,0.0,16.0,3.0,5.0,37.0,2022-02-15,1.0
4,2022,AC,1.0,1200351.0,4.0,NaN,0.0,NaN,1.0,5.0,42.0,2022-01-17,1.0

In [15]:
import pandas as pd
from google.colab import files
import io

print("Por favor, selecione o segundo arquivo CSV para df2:")
uploaded_df2 = files.upload()

# Assuming only one file is uploaded
for filename in uploaded_df2.keys():
  df2 = pd.read_csv(io.BytesIO(uploaded_df2[filename]))
  print(f"O arquivo '{filename}' foi carregado com sucesso em df2.")
  display(df2.head())
  break # Process only the first uploaded file

Por favor, selecione o segundo arquivo CSV para df2:

Saving dados_sinasc_trabalho_projeto_2023.csv to dados_sinasc_trabalho_projeto_2023.csv
O arquivo 'dados_sinasc_trabalho_projeto_2023.csv' foi carregado com sucesso em df2.

,ano,sigla_uf,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,data_nascimento,tipo_parto_1
0,2023,BA,1.0,2924009.0,0.0,0.0,0.0,21.0,4.0,4.0,40.0,2023-02-27,1.0
1,2023,BA,1.0,NaN,0.0,NaN,NaN,19.0,4.0,NaN,36.0,2023-04-06,1.0
2,2023,AM,1.0,1303700.0,0.0,0.0,0.0,15.0,3.0,4.0,38.0,2023-02-19,1.0
3,2023,CE,1.0,2304400.0,NaN,NaN,NaN,37.0,3.0,4.0,37.0,2023-01-30,1.0
4,2023,RR,1.0,1400456.0,0.0,0.0,0.0,17.0,4.0,5.0,36.0,2023-04-02,1.0

In [16]:
print("--- Informações do DataFrame 1 (df1) ---")
df1.info()
print("\n--- Primeiras 5 linhas do DataFrame 1 (df1) ---")
display(df1.head())
print("\n--- Estatísticas Descritivas do DataFrame 1 (df1) ---")
display(df1.describe())
print("\n--- Contagem de valores nulos por coluna no DataFrame 1 (df1) ---")
display(df1.isnull().sum())

--- Informações do DataFrame 1 (df1) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2560319 entries, 0 to 2560318
Data columns (total 13 columns):
 #   Column                    Dtype
---  ------                    -----
 0   ano                       int64
 1   sigla_uf                  object
 2   tipo_parto                float64
 3   id_municipio_mae          float64
 4   quantidade_filhos_vivos   float64
 5   quantidade_parto_normal   float64
 6   quantidade_parto_cesareo  float64
 7   idade_mae                 float64
 8   escolaridade_mae          float64
 9   raca_cor_mae              float64
 10  semana_gestacao           float64
 11  data_nascimento           object
 12  tipo_parto_1              float64
dtypes: float64(10), int64(1), object(2)
memory usage: 253.9+ MB

--- Primeiras 5 linhas do DataFrame 1 (df1) ---

,ano,sigla_uf,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,data_nascimento,tipo_parto_1
0,2022,AC,1.0,1200344.0,4.0,4.0,0.0,24.0,1.0,5.0,35.0,2022-03-18,1.0
1,2022,AC,1.0,1200328.0,2.0,2.0,0.0,15.0,4.0,5.0,34.0,2022-12-30,1.0
2,2022,AC,9.0,1200351.0,5.0,5.0,0.0,34.0,1.0,5.0,38.0,2022-01-20,9.0
3,2022,AC,1.0,1200328.0,1.0,1.0,0.0,16.0,3.0,5.0,37.0,2022-02-15,1.0
4,2022,AC,1.0,1200351.0,4.0,NaN,0.0,NaN,1.0,5.0,42.0,2022-01-17,1.0

--- Estatísticas Descritivas do DataFrame 1 (df1) ---

,ano,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,tipo_parto_1
count,2560319.0,2.558712e+06,2.483968e+06,2.519376e+06,2.497097e+06,2.489118e+06,2.560295e+06,2.547182e+06,2.491955e+06,2.535709e+06,2.558712e+06
mean,2022.0,1.581660e+00,3.112783e+06,1.032946e+00,6.683765e-01,4.025056e-01,2.755327e+01,4.113964e+00,2.837457e+00,3.836427e+01,1.581660e+00
std,0.0,4.949476e-01,9.842858e+05,1.317357e+00,1.299883e+00,8.685200e-01,6.735623e+00,7.216184e-01,1.422090e+00,2.229701e+00,4.949476e-01
min,2022.0,1.000000e+00,1.100015e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.900000e+01,1.000000e+00
25%,2022.0,1.000000e+00,2.414407e+06,0.000000e+00,0.000000e+00,0.000000e+00,2.200000e+01,4.000000e+00,1.000000e+00,3.800000e+01,1.000000e+00
50%,2022.0,2.000000e+00,3.140001e+06,1.000000e+00,0.000000e+00,0.000000e+00,2.700000e+01,4.000000e+00,4.000000e+00,3.900000e+01,2.000000e+00
75%,2022.0,2.000000e+00,3.550308e+06,2.000000e+00,1.000000e+00,1.000000e+00,3.300000e+01,4.000000e+00,4.000000e+00,4.000000e+01,2.000000e+00
max,2022.0,9.000000e+00,5.300108e+06,9.900000e+01,9.900000e+01,9.900000e+01,9.900000e+01,9.000000e+00,5.000000e+00,4.500000e+01,9.000000e+00

--- Contagem de valores nulos por coluna no DataFrame 1 (df1) ---

ano                             0
sigla_uf                        0
tipo_parto                   1607
id_municipio_mae            76351
quantidade_filhos_vivos     40943
quantidade_parto_normal     63222
quantidade_parto_cesareo    71201
idade_mae                      24
escolaridade_mae            13137
raca_cor_mae                68364
semana_gestacao             24610
data_nascimento                 0
tipo_parto_1                 1607
dtype: int64

---

In [17]:
print("--- Informações do DataFrame 2 (df2) ---")
df2.info()
print("\n--- Primeiras 5 linhas do DataFrame 2 (df2) ---")
display(df2.head())
print("\n--- Estatísticas Descritivas do DataFrame 2 (df2) ---")
display(df2.describe())
print("\n--- Contagem de valores nulos por coluna no DataFrame 2 (df2) ---")
display(df2.isnull().sum())

--- Informações do DataFrame 2 (df2) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986591 entries, 0 to 986590
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ano                       986591 non-null  int64
 1   sigla_uf                  986591 non-null  object
 2   tipo_parto                985765 non-null  float64
 3   id_municipio_mae          955939 non-null  float64
 4   quantidade_filhos_vivos   970437 non-null  float64
 5   quantidade_parto_normal   963119 non-null  float64
 6   quantidade_parto_cesareo  960889 non-null  float64
 7   idade_mae                 986585 non-null  float64
 8   escolaridade_mae          982065 non-null  float64
 9   raca_cor_mae              963459 non-null  float64
 10  semana_gestacao           977093 non-null  float64
 11  data_nascimento           986591 non-null  object
 12  tipo_parto_1              985765 non-null  float64
dtypes: float64(10), int64(1), object(2)
memory usage: 97.9+ MB

--- Primeiras 5 linhas do DataFrame 2 (df2) ---

,ano,sigla_uf,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,data_nascimento,tipo_parto_1
0,2023,BA,1.0,2924009.0,0.0,0.0,0.0,21.0,4.0,4.0,40.0,2023-02-27,1.0
1,2023,BA,1.0,NaN,0.0,NaN,NaN,19.0,4.0,NaN,36.0,2023-04-06,1.0
2,2023,AM,1.0,1303700.0,0.0,0.0,0.0,15.0,3.0,4.0,38.0,2023-02-19,1.0
3,2023,CE,1.0,2304400.0,NaN,NaN,NaN,37.0,3.0,4.0,37.0,2023-01-30,1.0
4,2023,RR,1.0,1400456.0,0.0,0.0,0.0,17.0,4.0,5.0,36.0,2023-04-02,1.0

--- Estatísticas Descritivas do DataFrame 2 (df2) ---

,ano,tipo_parto,id_municipio_mae,quantidade_filhos_vivos,quantidade_parto_normal,quantidade_parto_cesareo,idade_mae,escolaridade_mae,raca_cor_mae,semana_gestacao,tipo_parto_1
count,986591.0,985765.000000,9.559390e+05,970437.000000,963119.000000,960889.000000,986585.000000,982065.000000,963459.000000,977093.000000,985765.000000
mean,2023.0,1.591417,3.131635e+06,1.029836,0.659526,0.415028,27.615480,4.119969,2.817269,38.248588,1.591417
std,0.0,0.492669,9.825581e+05,1.476938,1.513851,1.184022,6.706933,0.687189,1.424110,2.228130,0.492669
min,2023.0,1.000000,1.100015e+06,0.000000,0.000000,0.000000,8.000000,1.000000,1.000000,19.000000,1.000000
25%,2023.0,1.000000,2.504009e+06,0.000000,0.000000,0.000000,22.000000,4.000000,1.000000,38.000000,1.000000
50%,2023.0,2.000000,3.148004e+06,1.000000,0.000000,0.000000,27.000000,4.000000,4.000000,39.000000,2.000000
75%,2023.0,2.000000,3.550308e+06,2.000000,1.000000,1.000000,33.000000,4.000000,4.000000,39.000000,2.000000
max,2023.0,9.000000,5.300108e+06,99.000000,99.000000,99.000000,99.000000,9.000000,5.000000,45.000000,9.000000

--- Contagem de valores nulos por coluna no DataFrame 2 (df2) ---

ano                             0
sigla_uf                        0
tipo_parto                    826
id_municipio_mae            30652
quantidade_filhos_vivos     16154
quantidade_parto_normal     23472
quantidade_parto_cesareo    25702
idade_mae                       6
escolaridade_mae             4526
raca_cor_mae                23132
semana_gestacao              9498
data_nascimento                 0
tipo_parto_1                  826
dtype: int64

## 3. Consistência de Colunas: `tipo_parto` vs `tipo_parto_1`

In [18]:
print("--- df1: Valores únicos e contagem para 'tipo_parto' ---")
display(df1['tipo_parto'].value_counts(dropna=False))

print("\n--- df1: Valores únicos e contagem para 'tipo_parto_1' ---")
display(df1['tipo_parto_1'].value_counts(dropna=False))

print("\n--- df2: Valores únicos e contagem para 'tipo_parto' ---")
display(df2['tipo_parto'].value_counts(dropna=False))

print("\n--- df2: Valores únicos e contagem para 'tipo_parto_1' ---")
display(df2['tipo_parto_1'].value_counts(dropna=False))

--- df1: Valores únicos e contagem para 'tipo_parto' ---

tipo_parto
2.0    1487701
1.0    1070936
NaN       1607
9.0         75
Name: count, dtype: int64

--- df1: Valores únicos e contagem para 'tipo_parto_1' ---

tipo_parto_1
2.0    1487701
1.0    1070936
NaN       1607
9.0         75
Name: count, dtype: int64

--- df2: Valores únicos e contagem para 'tipo_parto' ---

tipo_parto
2.0    582846
1.0    402900
NaN       826
9.0        19
Name: count, dtype: int64

--- df2: Valores únicos e contagem para 'tipo_parto_1' ---

tipo_parto_1
2.0    582846
1.0    402900
NaN       826
9.0        19
Name: count, dtype: int64

In [19]:
print("--- Verificando se 'tipo_parto' e 'tipo_parto_1' são idênticos em df1 ---")
display(df1['tipo_parto'].equals(df1['tipo_parto_1']))

print("\n--- Verificando diferenças entre 'tipo_parto' e 'tipo_parto_1' em df1 ---")
display(df1[df1['tipo_parto'] != df1['tipo_parto_1']][['tipo_parto', 'tipo_parto_1']].drop_duplicates())

print("\n--- Verificando se 'tipo_parto' e 'tipo_parto_1' são idênticos em df2 ---")
display(df2['tipo_parto'].equals(df2['tipo_parto_1']))

print("\n--- Verificando diferenças entre 'tipo_parto' e 'tipo_parto_1' em df2 ---")
display(df2[df2['tipo_parto'] != df2['tipo_parto_1']][['tipo_parto', 'tipo_parto_1']].drop_duplicates())

--- Verificando se 'tipo_parto' e 'tipo_parto_1' são idênticos em df1 ---

True

--- Verificando diferenças entre 'tipo_parto' e 'tipo_parto_1' em df1 ---

       tipo_parto  tipo_parto_1
16432         NaN           NaN

--- Verificando se 'tipo_parto' e 'tipo_parto_1' são idênticos em df2 ---

True

--- Verificando diferenças entre 'tipo_parto' e 'tipo_parto_1' em df2 ---

    tipo_parto  tipo_parto_1
95         NaN           NaN